name: Generate snake game

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # passo obrigatório para acessar o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # gera o snake game SVG a partir do gráfico de contribuições
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # publica os SVGs no branch 'output'
      - name: Deploy SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
